<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

global $wpdb;

$oby_mi_erp_show_form = oby_mi_erp_query_has( 'new' ) || oby_mi_erp_query_has( 'view' );
$oby_mi_erp_view_id   = oby_mi_erp_query_int( 'view' );
$oby_mi_erp_accounts  = oby_mi_erp_get_accounts();

$oby_mi_erp_search = oby_mi_erp_query_text( 's' );

$oby_mi_erp_per_page = 20;
$oby_mi_erp_paged    = max( 1, oby_mi_erp_query_int( 'paged', 1 ) );

if ( $oby_mi_erp_search ) {
	$oby_mi_erp_like = '%' . $wpdb->esc_like( $oby_mi_erp_search ) . '%';
	$oby_mi_erp_total_items = (int) $wpdb->get_var( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- filtered admin list query; caching would multiply keys by every filter/page combo without meaningful benefit.
		$wpdb->prepare(
			"SELECT COUNT(*) FROM {$wpdb->prefix}oby_mi_erp_journal_entries WHERE description LIKE %s",
			$oby_mi_erp_like
		)
	);
} else {
	$oby_mi_erp_total_items = (int) $wpdb->get_var( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- filtered admin list query; caching would multiply keys by every filter/page combo without meaningful benefit.
		$wpdb->prepare(
			"SELECT COUNT(*) FROM {$wpdb->prefix}oby_mi_erp_journal_entries WHERE 1 = %d",
			1
		)
	);
}

$oby_mi_erp_total_pages = max( 1, (int) ceil( $oby_mi_erp_total_items / $oby_mi_erp_per_page ) );
$oby_mi_erp_paged       = min( $oby_mi_erp_paged, $oby_mi_erp_total_pages );
$oby_mi_erp_offset      = ( $oby_mi_erp_paged - 1 ) * $oby_mi_erp_per_page;

if ( $oby_mi_erp_search ) {
	$oby_mi_erp_like   = '%' . $wpdb->esc_like( $oby_mi_erp_search ) . '%';
	$oby_mi_erp_entries = $wpdb->get_results( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- filtered admin list query; caching would multiply keys by every filter/page combo without meaningful benefit.
		$wpdb->prepare(
			"SELECT * FROM {$wpdb->prefix}oby_mi_erp_journal_entries WHERE description LIKE %s ORDER BY entry_date DESC, id DESC LIMIT %d OFFSET %d",
			$oby_mi_erp_like,
			$oby_mi_erp_per_page,
			$oby_mi_erp_offset
		)
	);
} else {
	$oby_mi_erp_entries = $wpdb->get_results( // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- filtered admin list query; caching would multiply keys by every filter/page combo without meaningful benefit.
		$wpdb->prepare(
			"SELECT * FROM {$wpdb->prefix}oby_mi_erp_journal_entries ORDER BY entry_date DESC, id DESC LIMIT %d OFFSET %d",
			$oby_mi_erp_per_page,
			$oby_mi_erp_offset
		)
	);
}

$oby_mi_erp_lines_by_entry = array();
if ( ! empty( $oby_mi_erp_entries ) ) {
	$oby_mi_erp_ids            = array_map( 'intval', array_column( $oby_mi_erp_entries, 'id' ) );
	$oby_mi_erp_in_placeholders = implode( ',', array_fill( 0, count( $oby_mi_erp_ids ), '%d' ) );
	$oby_mi_erp_lines          = $wpdb->get_results( $wpdb->prepare( "SELECT l.*, a.code, a.name FROM {$wpdb->prefix}oby_mi_erp_journal_lines l INNER JOIN {$wpdb->prefix}oby_mi_erp_accounts a ON a.id = l.account_id WHERE l.entry_id IN ({$oby_mi_erp_in_placeholders}) ORDER BY l.id ASC", $oby_mi_erp_ids ) ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.NotPrepared, WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.PreparedSQLPlaceholders.UnfinishedPrepare -- derived value recomputed per request; IN-clause placeholders generated by array_fill count, values passed as array args.
	foreach ( $oby_mi_erp_lines as $oby_mi_erp_line ) {
		$oby_mi_erp_lines_by_entry[ $oby_mi_erp_line->entry_id ][] = $oby_mi_erp_line;
	}
}

oby_mi_erp_print_admin_notice();

$oby_mi_erp_back_url = oby_mi_erp_admin_url( 'journal' );
$oby_mi_erp_from     = oby_mi_erp_query_key( 'from' );
if ( $oby_mi_erp_from && ! in_array( $oby_mi_erp_from, array( 'income', 'expense' ), true ) ) {
	$oby_mi_erp_from = '';
}
if ( $oby_mi_erp_from ) {
	$oby_mi_erp_back_url = oby_mi_erp_admin_url( $oby_mi_erp_from );
}

if ( $oby_mi_erp_view_id ) {
	$oby_mi_erp_view_entry = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}oby_mi_erp_journal_entries WHERE id = %d", $oby_mi_erp_view_id ) ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- single-row lookup gating a write flow; caches are flushed downstream.
	$oby_mi_erp_view_lines = isset( $oby_mi_erp_lines_by_entry[ $oby_mi_erp_view_id ] ) ? $oby_mi_erp_lines_by_entry[ $oby_mi_erp_view_id ] : array();
}
?>
<div class="wrap oby-mi-erp-page">
	<h1 class="wp-heading-inline mb-3">
		<?php
		if ( $oby_mi_erp_show_form && $oby_mi_erp_view_id ) {
			esc_html_e( 'View Journal Entry', 'obydullah-micro-erp' );
		} elseif ( $oby_mi_erp_show_form ) {
			esc_html_e( 'New Journal Entry', 'obydullah-micro-erp' );
		} else {
			esc_html_e( 'Journal Entries', 'obydullah-micro-erp' );
		}
		?>
		<?php if ( ! $oby_mi_erp_show_form ) : ?>
			<a href="<?php echo esc_url( oby_mi_erp_admin_url( 'journal', array( 'new' => '1' ) ) ); ?>" class="btn-primary"><?php esc_html_e( '+ New Entry', 'obydullah-micro-erp' ); ?></a>
		<?php endif; ?>
	</h1>
	<hr class="wp-header-end">

	<?php if ( $oby_mi_erp_show_form && $oby_mi_erp_view_id ) : ?>

		<div class="row mt-3">
			<div class="col-lg-12">
				<div class="bg-light p-3 rounded shadow-sm border">
					<h2 class="h5 mb-3 fw-semibold"><?php echo esc_html( $oby_mi_erp_view_entry->description ); ?></h2>
					<div class="table-responsive">
						<table class="table table-striped table-hover table-bordered mb-2">
							<thead>
								<tr class="bg-primary text-white">
									<th><?php esc_html_e( 'Account', 'obydullah-micro-erp' ); ?></th>
									<th><?php esc_html_e( 'Description', 'obydullah-micro-erp' ); ?></th>
									<th width="140" class="text-right"><?php esc_html_e( 'Debit', 'obydullah-micro-erp' ); ?></th>
									<th width="140" class="text-right"><?php esc_html_e( 'Credit', 'obydullah-micro-erp' ); ?></th>
								</tr>
							</thead>
							<tbody class="bg-white">
								<?php
								$oby_mi_erp_td = 0;
								$oby_mi_erp_tc = 0;
								foreach ( $oby_mi_erp_view_lines as $oby_mi_erp_line ) :
									$oby_mi_erp_td += (float) $oby_mi_erp_line->debit;
									$oby_mi_erp_tc += (float) $oby_mi_erp_line->credit;
									?>
									<tr>
										<td><?php echo esc_html( $oby_mi_erp_line->code . ' - ' . $oby_mi_erp_line->name ); ?></td>
										<td><?php echo esc_html( $oby_mi_erp_line->description ); ?></td>
										<td class="text-right"><?php echo esc_html( oby_mi_erp_format_money( $oby_mi_erp_line->debit ) ); ?></td>
										<td class="text-right"><?php echo esc_html( oby_mi_erp_format_money( $oby_mi_erp_line->credit ) ); ?></td>
									</tr>
								<?php endforeach; ?>
								<tr class="total-row">
									<td colspan="2"><strong><?php esc_html_e( 'Total', 'obydullah-micro-erp' ); ?></strong></td>
									<td class="text-right"><strong><?php echo esc_html( oby_mi_erp_format_money( $oby_mi_erp_td ) ); ?></strong></td>
									<td class="text-right"><strong><?php echo esc_html( oby_mi_erp_format_money( $oby_mi_erp_tc ) ); ?></strong></td>
								</tr>
							</tbody>
						</table>
					</div>
					<a href="<?php echo esc_url( $oby_mi_erp_back_url ); ?>" class="btn-secondary mt-2 d-inline-block">← <?php echo esc_html( $oby_mi_erp_from ? __( 'Back to ', 'obydullah-micro-erp' ) . ( 'expense' === $oby_mi_erp_from ? __( 'Expenses', 'obydullah-micro-erp' ) : __( 'Income', 'obydullah-micro-erp' ) ) : __( 'Back to Journal', 'obydullah-micro-erp' ) ); ?></a>
				</div>
			</div>
		</div>

	<?php elseif ( $oby_mi_erp_show_form ) : ?>

		<form method="post" action="">
			<?php wp_nonce_field( 'oby_mi_erp_journal_save' ); ?>
			<input type="hidden" name="oby_mi_erp_action" value="save_journal">
			<input type="hidden" name="oby_mi_erp_redirect" value="<?php echo esc_url( $oby_mi_erp_back_url ); ?>">

			<div class="row mt-3">
				<div class="col-lg-6 col-md-12">
					<div class="bg-light p-4 rounded shadow-sm mb-4">
						<h2 class="mb-3 mt-1"><?php esc_html_e( 'Entry Details', 'obydullah-micro-erp' ); ?></h2>

						<div class="mb-3">
							<label for="entry_date" class="form-label"><?php esc_html_e( 'Date', 'obydullah-micro-erp' ); ?> <span class="text-danger">*</span></label>
							<input type="date" name="entry_date" id="entry_date" class="form-control" value="<?php echo esc_attr( current_time( 'Y-m-d' ) ); ?>" required>
						</div>

						<div class="mb-3">
							<label for="description" class="form-label"><?php esc_html_e( 'Description', 'obydullah-micro-erp' ); ?> <span class="text-danger">*</span></label>
							<input type="text" name="description" id="description" class="form-control" placeholder="<?php esc_attr_e( 'Brief description of this entry', 'obydullah-micro-erp' ); ?>" required>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-12">
					<div class="bg-light p-4 rounded shadow-sm mb-4">
						<h2 class="mb-3 mt-1"><?php esc_html_e( 'Journal Lines', 'obydullah-micro-erp' ); ?></h2>

						<table class="journal-lines table table-striped table-hover table-bordered" id="journal-lines">
							<thead>
								<tr class="bg-primary text-white">
									<th style="width:30%;"><?php esc_html_e( 'Account', 'obydullah-micro-erp' ); ?></th>
									<th><?php esc_html_e( 'Description', 'obydullah-micro-erp' ); ?></th>
									<th width="130"><?php esc_html_e( 'Debit', 'obydullah-micro-erp' ); ?></th>
									<th width="130"><?php esc_html_e( 'Credit', 'obydullah-micro-erp' ); ?></th>
									<th width="50"></th>
								</tr>
							</thead>
							<tbody class="bg-white">
								<tr>
									<td>
										<select name="account_id[]" required class="form-control form-control-sm">
											<option value=""><?php esc_html_e( 'Select Account', 'obydullah-micro-erp' ); ?></option>
											<?php foreach ( $oby_mi_erp_accounts as $oby_mi_erp_acct ) : ?>
												<option value="<?php echo (int) $oby_mi_erp_acct->id; ?>"><?php echo esc_html( $oby_mi_erp_acct->code . ' - ' . $oby_mi_erp_acct->name ); ?></option>
											<?php endforeach; ?>
										</select>
									</td>
									<td><input type="text" name="line_description[]" class="form-control form-control-sm"></td>
									<td><input type="number" name="debit[]" class="j-debit form-control form-control-sm text-right" step="0.01" min="0" placeholder="0.00"></td>
									<td><input type="number" name="credit[]" class="j-credit form-control form-control-sm text-right" step="0.01" min="0" placeholder="0.00"></td>
									<td><button type="button" class="btn-danger j-remove">×</button></td>
								</tr>
								<tr>
									<td>
										<select name="account_id[]" required class="form-control form-control-sm">
											<option value=""><?php esc_html_e( 'Select Account', 'obydullah-micro-erp' ); ?></option>
											<?php foreach ( $oby_mi_erp_accounts as $oby_mi_erp_acct ) : ?>
												<option value="<?php echo (int) $oby_mi_erp_acct->id; ?>"><?php echo esc_html( $oby_mi_erp_acct->code . ' - ' . $oby_mi_erp_acct->name ); ?></option>
											<?php endforeach; ?>
										</select>
									</td>
									<td><input type="text" name="line_description[]" class="form-control form-control-sm"></td>
									<td><input type="number" name="debit[]" class="j-debit form-control form-control-sm text-right" step="0.01" min="0" placeholder="0.00"></td>
									<td><input type="number" name="credit[]" class="j-credit form-control form-control-sm text-right" step="0.01" min="0" placeholder="0.00"></td>
									<td><button type="button" class="btn-danger j-remove">×</button></td>
								</tr>
							</tbody>
							<tfoot>
								<tr class="total-row">
									<td colspan="2"><strong><?php esc_html_e( 'Total', 'obydullah-micro-erp' ); ?></strong></td>
									<td class="text-right"><strong class="j-total-debit">0.00</strong></td>
									<td class="text-right"><strong class="j-total-credit">0.00</strong></td>
									<td></td>
								</tr>
							</tfoot>
						</table>

						<button type="button" class="btn-primary j-add-line mt-3"><?php esc_html_e( '+ Add Line', 'obydullah-micro-erp' ); ?></button>
						<p class="j-balance-note form-text mt-1"><?php esc_html_e( 'Debit and Credit totals must be equal.', 'obydullah-micro-erp' ); ?></p>
					</div>
				</div>
			</div>

			<div class="d-flex mt-2 mb-4">
				<a href="<?php echo esc_url( $oby_mi_erp_back_url ); ?>" class="btn-secondary mr-2"><?php esc_html_e( 'Cancel', 'obydullah-micro-erp' ); ?></a>
				<button type="submit" class="btn-success"><?php esc_html_e( 'Save Journal Entry', 'obydullah-micro-erp' ); ?></button>
			</div>
		</form>

	<?php else : ?>

		<div class="row mt-3">
		<div class="col-lg-12">
			<?php oby_mi_erp_render_search_bar( 'journal', __( 'Search Entries', 'obydullah-micro-erp' ), __( 'Search by description...', 'obydullah-micro-erp' ), array(), $oby_mi_erp_search ); ?>
		</div>
	</div>

	<div class="row mt-1">
			<div class="col-lg-12">
				<div class="bg-light p-3 rounded shadow-sm border">
					<h2 class="h5 mb-3 fw-semibold"><?php esc_html_e( 'All Entries', 'obydullah-micro-erp' ); ?></h2>

					<div class="table-responsive">
						<table class="table table-striped table-hover table-bordered mb-2">
							<thead>
								<tr class="bg-primary text-white">
									<th width="110"><?php esc_html_e( 'Date', 'obydullah-micro-erp' ); ?></th>
									<th width="80">#</th>
									<th><?php esc_html_e( 'Description', 'obydullah-micro-erp' ); ?></th>
									<th><?php esc_html_e( 'Source', 'obydullah-micro-erp' ); ?></th>
									<th width="130" class="text-right"><?php esc_html_e( 'Debit', 'obydullah-micro-erp' ); ?></th>
									<th width="130" class="text-right"><?php esc_html_e( 'Credit', 'obydullah-micro-erp' ); ?></th>
									<th width="150" class="text-right"><?php esc_html_e( 'Actions', 'obydullah-micro-erp' ); ?></th>
								</tr>
							</thead>
							<tbody class="bg-white">
								<?php if ( empty( $oby_mi_erp_entries ) ) : ?>
									<tr><td colspan="7" class="text-center p-4"><?php esc_html_e( 'No journal entries yet.', 'obydullah-micro-erp' ); ?></td></tr>
								<?php endif; ?>
								<?php foreach ( $oby_mi_erp_entries as $oby_mi_erp_entry ) :
									$oby_mi_erp_entry_lines = isset( $oby_mi_erp_lines_by_entry[ $oby_mi_erp_entry->id ] ) ? $oby_mi_erp_lines_by_entry[ $oby_mi_erp_entry->id ] : array();
									$oby_mi_erp_t_d = 0;
									$oby_mi_erp_t_c = 0;
									foreach ( $oby_mi_erp_entry_lines as $oby_mi_erp_line ) {
										$oby_mi_erp_t_d += (float) $oby_mi_erp_line->debit;
										$oby_mi_erp_t_c += (float) $oby_mi_erp_line->credit;
									}
									?>
									<tr>
										<td><?php echo esc_html( $oby_mi_erp_entry->entry_date ); ?></td>
										<td>JE-<?php echo (int) $oby_mi_erp_entry->id; ?></td>
										<td><strong><?php echo esc_html( $oby_mi_erp_entry->description ); ?></strong></td>
										<td><?php echo esc_html( $oby_mi_erp_entry->reference_type ? ucwords( str_replace( '_', ' ', $oby_mi_erp_entry->reference_type ) ) : '—' ); ?></td>
										<td class="text-right"><?php echo esc_html( oby_mi_erp_format_money( $oby_mi_erp_t_d ) ); ?></td>
										<td class="text-right"><?php echo esc_html( oby_mi_erp_format_money( $oby_mi_erp_t_c ) ); ?></td>
										<td>
											<div class="pos-row-actions">
												<a href="<?php echo esc_url( oby_mi_erp_admin_url( 'journal', array( 'view' => $oby_mi_erp_entry->id ) ) ); ?>" class="pos-action edit pos-icon" aria-label="<?php esc_attr_e( 'View', 'obydullah-micro-erp' ); ?>" title="<?php esc_attr_e( 'View', 'obydullah-micro-erp' ); ?>"><span class="dashicons dashicons-visibility" aria-hidden="true"></span></a>
												<form method="post" action="" class="inline-form" onsubmit="return confirm('<?php esc_attr_e( 'Delete this entry?', 'obydullah-micro-erp' ); ?>');">
													<?php wp_nonce_field( 'oby_mi_erp_journal_delete' ); ?>
													<input type="hidden" name="oby_mi_erp_action" value="delete_journal">
													<input type="hidden" name="id" value="<?php echo (int) $oby_mi_erp_entry->id; ?>">
													<input type="hidden" name="oby_mi_erp_redirect" value="<?php echo esc_url( $oby_mi_erp_back_url ); ?>">
													<button class="pos-action delete pos-icon" aria-label="<?php esc_attr_e( 'Delete', 'obydullah-micro-erp' ); ?>" title="<?php esc_attr_e( 'Delete', 'obydullah-micro-erp' ); ?>"><span class="dashicons dashicons-trash" aria-hidden="true"></span></button>
												</form>
											</div>
										</td>
									</tr>
								<?php endforeach; ?>
							</tbody>
						</table>
					</div>

					<?php oby_mi_erp_render_pagination( 'journal', $oby_mi_erp_total_items, $oby_mi_erp_per_page ); ?>

				</div>
			</div>
		</div>

	<?php endif; ?>
</div>
